apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: redahimmi/national-transfer-api-gateway
        env:
          - name: "EUREKA_CLIENT_ENABLED"
            value: "false"

          - name: "SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED"
            value: "true"
          
          - name: "SPRING_CLOUD_KUBERNETES_DISCOVERY_NAMESPACES"
            value: "prod"
            
          - name: "SPRING_CLOUD_KUBERNETES_DISCOVERY_DISCOVERYSERVERURL"
            value: "http://spring-cloud-kubernetes-discoveryserver.default.svc.cluster.local"

          - name: "SPRING_CLOUD_KUBERNETES_LOADBALANCER_ENABLED"
            value: "true"
          
          - name: "SPRING_CONFIG_IMPORT"
            value: "optional:configserver:http://config@secret@config-server"

        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 8091