apiVersion: apps/v1
kind: Deployment
metadata:
  name: gab
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gab
  template:
    metadata:
      labels:
        app: gab
    spec:
      containers:
      - name: gab
        image: redahimmi/national-transfer-gab-service
        env:
          - name: "SPRING_DATASOURCE_URL"
            value: "jdbc:mysql://national-transfer.mysql.database.azure.com:3306/gabDB"
          - name: "SPRING_DATASOURCE_USERNAME"
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: SPRING_DATASOURCE_USERNAME 
          - name: "SPRING_DATASOURCE_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: SPRING_DATASOURCE_PASSWORD

          - name: "EUREKA_CLIENT_ENABLED"
            value: "false"

          - name: "SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED"
            value: "true"
          
          - name: "SPRING_CLOUD_KUBERNETES_DISCOVERY_NAMESPACES"
            value: "prod"
            
          - name: "SPRING_CLOUD_KUBERNETES_DISCOVERY_DISCOVERYSERVERURL"
            value: "http://spring-cloud-kubernetes-discoveryserver.prod"

          - name: "SPRING_CLOUD_KUBERNETES_LOADBALANCER_ENABLED"
            value: "true"
          
          - name: "SPRING_CONFIG_IMPORT"
            value: "optional:configserver:http://config:secret@config-server.prod"

        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
        imagePullPolicy: Always
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health/readiness
        #     port: 8087
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health/liveness
        #     port: 8087
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        
        ports:
        - containerPort: 8087
