apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - gab-deployment.yml
# - gab-service.yml
# - discoveryserver.yml
resources:
- account-deployment.yml
- account-service.yml
- agency-deployment.yml
- agency-service.yml
- api-gateway-deployment.yml
- api-gateway-service.yml
- batch-deployment.yml
- batch-service.yml
- charge-deployment.yml
- charge-service.yml
- configserver-deployment.yml
- configserver-service.yml
- databaseSecret.yml
- fraud-deployment.yml
- fraud-service.yml
- ingress.yml
- kyc-deployment.yml
- kyc-service.yml
- namespace.yml
- notification-deployment.yml
- notification-service.yml
- production-issuer.yml
- rabbitmq-deployment.yml
- rabbitmq-service.yml
- staging-issuer.yml
- transfer-deployment.yml
- transfer-service.yml
images:
- name: redahimmi/national-transfer-account-service
  newName: redahimmi/national-transfer-account-service
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
- name: redahimmi/national-transfer-agency-service
  newName: redahimmi/national-transfer-agency-service
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
- name: redahimmi/national-transfer-api-gateway
  newName: redahimmi/national-transfer-api-gateway
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
- name: redahimmi/national-transfer-batch-service
  newName: redahimmi/national-transfer-batch-service
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
- name: redahimmi/national-transfer-charge-service
  newName: redahimmi/national-transfer-charge-service
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
- name: redahimmi/national-transfer-config-server
  newName: redahimmi/national-transfer-config-server
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
- name: redahimmi/national-transfer-fraud-service
  newName: redahimmi/national-transfer-fraud-service
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
- name: redahimmi/national-transfer-kyc-service
  newName: redahimmi/national-transfer-kyc-service
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
- name: redahimmi/national-transfer-notification-service
  newName: redahimmi/national-transfer-notification-service
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
- name: redahimmi/national-transfer-transfer-service
  newName: redahimmi/national-transfer-transfer-service
  newTag: d27da2e3b361071e028ec51b40cc2c51ecaf98b9
